// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiom3PFzaZTpIrXBDtsfPG9-w_WTh81U8',
    appId: '1:1046344754665:web:4180ad186f2c489b8d9778',
    messagingSenderId: '1046344754665',
    projectId: 'gocode-app',
    authDomain: 'gocode-app.firebaseapp.com',
    storageBucket: 'gocode-app.firebasestorage.app',
    measurementId: 'G-XJ884ESYPN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnxKPOYXTSpsrpISLECJ8b4FwSyRu9tPY',
    appId: '1:1046344754665:android:d4b34ba33e52ed888d9778',
    messagingSenderId: '1046344754665',
    projectId: 'gocode-app',
    storageBucket: 'gocode-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgqD9kfQJAobq5iCYBIZsmwPPwH4ub2tk',
    appId: '1:1046344754665:ios:4543ab8f3af4a2a78d9778',
    messagingSenderId: '1046344754665',
    projectId: 'gocode-app',
    storageBucket: 'gocode-app.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgqD9kfQJAobq5iCYBIZsmwPPwH4ub2tk',
    appId: '1:1046344754665:ios:4543ab8f3af4a2a78d9778',
    messagingSenderId: '1046344754665',
    projectId: 'gocode-app',
    storageBucket: 'gocode-app.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCiom3PFzaZTpIrXBDtsfPG9-w_WTh81U8',
    appId: '1:1046344754665:web:1c17c58f110bdc728d9778',
    messagingSenderId: '1046344754665',
    projectId: 'gocode-app',
    authDomain: 'gocode-app.firebaseapp.com',
    storageBucket: 'gocode-app.firebasestorage.app',
    measurementId: 'G-NFWW9M772H',
  );
}
